# Dashboard Demo
Genera el dataset, las gráficas interactivas (con filtros) y arma el dashboard final en `dashboard.html`.

In [1]:
import pandas as pd
import plotly.graph_objects as go
import numpy as np
import json

## 1. Dataset falso

In [2]:
# ============================================
# CONFIGURA AQUÍ: cambia estos datos por los tuyos
# ============================================
meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio']
data_mensual = pd.DataFrame({
    'Mes': meses,
    'Ventas': [45000, 52000, 48000, 61000, 58000, 67000],
    'Unidades': [180, 210, 195, 240, 225, 265]
})

productos = ['Producto A', 'Producto B', 'Producto C']
data_producto = pd.DataFrame({
    'Producto': productos,
    'Ingreso': [48000, 31500, 63000],
    'Unidades': [320, 210, 150]
})

data_producto

     Producto  Ingreso  Unidades
0  Producto A    48000       320
1  Producto B    31500       210
2  Producto C    63000       150

## 2. Gráfica 1 — Línea con filtro (Ventas / Unidades)
Esta va del lado **izquierdo**, ocupando todo el alto.

In [3]:
fig_linea = go.Figure()
fig_linea.add_trace(go.Scatter(x=data_mensual['Mes'], y=data_mensual['Ventas'],
                                mode='lines+markers', name='Ventas',
                                line=dict(color='#2563eb', width=3)))
fig_linea.add_trace(go.Scatter(x=data_mensual['Mes'], y=data_mensual['Unidades'],
                                mode='lines+markers', name='Unidades',
                                line=dict(color='#16a34a', width=3), visible=False))

fig_linea.update_layout(
    title='Tendencia Mensual',
    updatemenus=[dict(
        type='dropdown', direction='down', x=1, xanchor='right', y=1.15,
        buttons=[
            dict(label='Ver Ventas', method='update',
                 args=[{'visible': [True, False]}, {'title': 'Tendencia Mensual — Ventas'}]),
            dict(label='Ver Unidades', method='update',
                 args=[{'visible': [False, True]}, {'title': 'Tendencia Mensual — Unidades'}]),
        ]
    )]
)
fig_linea.show()

## 3. Gráfica 2 — Barras con filtro (Ingreso / Unidades)
Esta va **arriba a la derecha**.

In [4]:
fig_barras = go.Figure()
fig_barras.add_trace(go.Bar(x=data_producto['Producto'], y=data_producto['Ingreso'],
                             name='Ingreso', marker_color='#2563eb', visible=True))
fig_barras.add_trace(go.Bar(x=data_producto['Producto'], y=data_producto['Unidades'],
                             name='Unidades', marker_color='#f59e0b', visible=False))

fig_barras.update_layout(
    title='Por Producto — Ingreso',
    updatemenus=[dict(
        type='dropdown', direction='down', x=1, xanchor='right', y=1.2,
        buttons=[
            dict(label='Ver Ingreso', method='update',
                 args=[{'visible': [True, False]}, {'title': 'Por Producto — Ingreso'}]),
            dict(label='Ver Unidades', method='update',
                 args=[{'visible': [False, True]}, {'title': 'Por Producto — Unidades'}]),
        ]
    )]
)
fig_barras.show()

## 4. Gráfica 3 — Pastel (distribución de unidades)
Esta va **abajo a la derecha**. El filtro aquí es nativo: clic en la leyenda oculta/muestra cada producto.

In [5]:
fig_pastel = go.Figure(data=[go.Pie(labels=data_producto['Producto'], values=data_producto['Unidades'])])
fig_pastel.update_layout(title='Distribución de Unidades')
fig_pastel.show()

## 5. Armar el dashboard final (`dashboard.html`)
Aquí se define el **orden y acomodo** de las gráficas en el grid. Para reacomodar, solo cambia qué figura va en cada posición (`grafica_izquierda`, `grafica_arriba_derecha`, `grafica_abajo_derecha`).

In [6]:
# ============================================
# CONFIGURA AQUÍ: qué gráfica va en cada posición del grid
# ============================================
grafica_izquierda = fig_linea
grafica_arriba_derecha = fig_barras
grafica_abajo_derecha = fig_pastel

html_izquierda = grafica_izquierda.to_html(full_html=False, include_plotlyjs='cdn', config={'responsive': True})
html_arriba = grafica_arriba_derecha.to_html(full_html=False, include_plotlyjs=False, config={'responsive': True})
html_abajo = grafica_abajo_derecha.to_html(full_html=False, include_plotlyjs=False, config={'responsive': True})

plantilla = '''<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>Dashboard</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; }
  body { background: #f3f4f6; padding: 20px; }
  .grid-dashboard {
    display: grid;
    grid-template-columns: 1.3fr 1fr;
    grid-template-rows: 1fr 1fr;
    gap: 16px;
    height: calc(100vh - 40px);
  }
  .panel {
    background: white;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.06);
    padding: 12px;
    overflow: hidden;
  }
  .panel-izquierda { grid-column: 1; grid-row: 1 / 3; }
  .panel-arriba-derecha { grid-column: 2; grid-row: 1; }
  .panel-abajo-derecha { grid-column: 2; grid-row: 2; }
  .panel > div { width: 100% !important; height: 100% !important; }
</style>
</head>
<body>
  <div class="grid-dashboard">
    <div class="panel panel-izquierda">__IZQUIERDA__</div>
    <div class="panel panel-arriba-derecha">__ARRIBA__</div>
    <div class="panel panel-abajo-derecha">__ABAJO__</div>
  </div>
</body>
</html>
'''

plantilla = plantilla.replace('__IZQUIERDA__', html_izquierda)
plantilla = plantilla.replace('__ARRIBA__', html_arriba)
plantilla = plantilla.replace('__ABAJO__', html_abajo)

with open('dashboard.html', 'w', encoding='utf-8') as f:
    f.write(plantilla)

print("dashboard.html generado")

dashboard.html generado

## 6. Data Quality — Load dataset
Loads the real dataset used for the Data Quality card in `data_quality.html`.

In [7]:
# ============================================
# CONFIGURE HERE: GitHub repo info
# ============================================
github_user = "elvaramosglz"
github_repo = "dashboard-demo"
github_branch = "main"
csv_filename = "dataset.csv"
dataset_encoding = "mac_roman"  # this file is saved as mac_roman, not UTF-8 (e.g. "Maracan\u00e3" breaks under utf-8)

# Built automatically \u2014 don't need to edit this line
dataset_url = f"https://raw.githubusercontent.com/{github_user}/{github_repo}/{github_branch}/{csv_filename}"

# Reads straight from GitHub, so anyone who opens this notebook gets the same
# CSV you have in the repo \u2014 no need to have the file saved locally
df_quality = pd.read_csv(dataset_url, encoding=dataset_encoding)
df_quality.head()

,MONTH,CITY,TRIPS,GROSS BOOKINGS (GB),SHOPPING SESSIONS,RIDERS WITH SESSIONS,REQUESTING SESSIONS,REQUESTS,ACTIVE DRIVERS,SUPPLY HOURS,...,RS/SS,C/SS,ACCEPTANCE RATE,DRIVER CANCELATION,SUPPLY UTILIZATION,NPI,DRIVER PAYMENTS (AS % OF GB),RIDER INCENTIVES AND PROMOTIONS (AS % OF GB),DRIVER INCENTIVES AND PROMOTIONS (AS % OF GB),TAKE RATE (AS % OF GB)
0,2022-01,Vila Belmiro,"3,005,706","56,529,569","5,283,006","711,432","3,257,826","3,844,423","18,795","1,564,816",...,61.7%,56.9%,23.0%,20.0%,63.0%,1.03,73.5%,5.7%,5.1%,14.2%
1,2022-01,Rose Bowl,"1,533,078","25,315,829","2,692,591","406,844","1,638,051","1,859,779","8,742","824,750",...,60.8%,56.9%,34.0%,15.0%,59.0%,0.98,76.3%,-3.3%,4.3%,20.5%
2,2022-01,San Siro,"8,108,570","155,667,588","14,385,079","1,609,850","8,570,326","9,515,128","50,056","4,187,961",...,59.6%,56.4%,44.0%,22.0%,73.0%,1.02,78.8%,4.9%,3.6%,10.6%
3,2022-01,Lusail,"2,163,550","38,225,180","3,939,724","493,960","2,348,175","2,859,544","10,845","1,074,968",...,59.6%,54.9%,25.0%,20.0%,70.0%,1.05,76.8%,6.2%,3.6%,11.8%
4,2022-01,Old Trafford,"11,042,462","206,436,144","19,113,887","2,553,885","11,801,188","13,152,423","63,551","5,202,255",...,61.7%,57.8%,46.0%,27.0%,77.0%,1.05,75.6%,-1.4%,3.4%,17.0%

## 7. Data Quality — completeness calculations
Completion %, null count, and coverage (cities/months) computed directly from the dataset.

In [8]:
total_rows = len(df_quality)
total_cols = len(df_quality.columns)
total_cells = total_rows * total_cols

null_count = int(df_quality.isna().sum().sum())
completeness_pct = round((1 - null_count / total_cells) * 100, 1)
completeness_pct_label = f"{completeness_pct:.0f}" if completeness_pct == int(completeness_pct) else f"{completeness_pct}"

n_cities = df_quality['CITY'].nunique()
n_months = df_quality['MONTH'].nunique()

if null_count == 0:
    summary_text = f"{total_rows} records \u00b7 {n_cities} cities \u00b7 {n_months} months \u00b7 no missing values"
else:
    summary_text = f"{total_rows} records \u00b7 {n_cities} cities \u00b7 {n_months} months \u00b7 {null_count} missing values"

completeness_pct, null_count, summary_text

(100.0, 0, '168 records · 8 cities · 21 months · no missing values')

## 8. Build the Data Quality card (`data_quality.html`)
Generates the hero card (Uber blue, compact, centered) using the values calculated above.

In [9]:
# ============================================
# CONFIGURE HERE: colors and label
# ============================================
uber_blue = '#276EF1'
card_label = 'Data Completeness'

data_quality_html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Data Quality</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; }}
  body {{
    background: #f3f4f6;
    padding: 24px;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
  }}

  .hero-card {{
    background: {uber_blue};
    color: #FFFFFF;
    border-radius: 16px;
    padding: 28px 40px;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: 4px;
    box-shadow: 0 4px 20px rgba(39,110,241,0.25);
    max-width: 320px;
  }}
  .hero-card .check {{ font-size: 32px; line-height: 1; margin-bottom: 4px; }}
  .hero-card .hero-number {{ font-size: 44px; font-weight: 700; line-height: 1; }}
  .hero-card .hero-label {{ font-size: 14px; font-weight: 600; opacity: 0.95; }}
  .hero-card .hero-sub {{ font-size: 11px; opacity: 0.8; }}
</style>
</head>
<body>

  <div class="hero-card">
    <div class="check">\u2705</div>
    <div class="hero-number">{completeness_pct_label}%</div>
    <div class="hero-label">{card_label}</div>
    <div class="hero-sub">{summary_text}</div>
  </div>

</body>
</html>
'''

with open('data_quality.html', 'w', encoding='utf-8') as f:
    f.write(data_quality_html)

print("data_quality.html generated")

data_quality.html generated

## 9. Data Quality — per-column breakdown
Calculates completeness, null count, and status per column. This feeds the dropdown in `data_quality.html`.

In [10]:
# ============================================
# CONFIGURE HERE: short description per column
# and the OK / warning / critical thresholds
# NOTE: "NPI" description below is a placeholder — confirm the real definition
# ============================================
column_descriptions = {
    "MONTH": "Reporting month for the record (YYYY-MM).",
    "CITY": "Market / city where the metrics were recorded.",
    "TRIPS": "Number of completed trips.",
    "GROSS BOOKINGS (GB)": "Total gross bookings value generated.",
    "SHOPPING SESSIONS": "App sessions where a rider browsed, not necessarily requesting a ride.",
    "RIDERS WITH SESSIONS": "Unique riders who opened a session.",
    "REQUESTING SESSIONS": "Sessions where the rider went on to request a ride.",
    "REQUESTS": "Total ride requests made.",
    "ACTIVE DRIVERS": "Unique drivers who were online during the period.",
    "SUPPLY HOURS": "Total hours drivers spent online and available.",
    "C/R": "Completion rate: completed trips over requests.",
    "C/RS": "Completion rate: completed trips over requesting sessions.",
    "RS/SS": "Conversion rate: requesting sessions over shopping sessions.",
    "C/SS": "Completion rate: completed trips over shopping sessions.",
    "ACCEPTANCE RATE": "Share of requests accepted by drivers.",
    "DRIVER CANCELATION": "Share of trips cancelled by drivers.",
    "SUPPLY UTILIZATION": "Share of available driver supply hours actually used.",
    "NPI": "Placeholder \u2014 confirm real definition.",
    "DRIVER PAYMENTS (AS % OF GB)": "Driver earnings as a percentage of gross bookings.",
    "RIDER INCENTIVES AND PROMOTIONS (AS % OF GB)": "Rider-side incentives/promos as a percentage of gross bookings.",
    "DRIVER INCENTIVES AND PROMOTIONS (AS % OF GB)": "Driver-side incentives/promos as a percentage of gross bookings.",
    "TAKE RATE (AS % OF GB)": "Platform\'s take rate as a percentage of gross bookings.",
}

ok_threshold = 98      # >= this % -> OK
warn_threshold = 90    # >= this % (and below ok_threshold) -> warning

column_stats = []
for col in df_quality.columns:
    nulls = int(df_quality[col].isna().sum())
    pct = round((1 - nulls / total_rows) * 100, 1)
    pct_label = f"{pct:.0f}" if pct == int(pct) else f"{pct}"
    if pct >= ok_threshold:
        status = "ok"
    elif pct >= warn_threshold:
        status = "warn"
    else:
        status = "bad"
    column_stats.append({
        "name": col,
        "description": column_descriptions.get(col, "No description yet."),
        "completeness": pct_label,
        "nulls": nulls,
        "total": total_rows,
        "status": status,
    })

column_stats

[{'name': 'MONTH',
  'description': 'Reporting month for the record (YYYY-MM).',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'CITY',
  'description': 'Market / city where the metrics were recorded.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'TRIPS',
  'description': 'Number of completed trips.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'GROSS BOOKINGS (GB)',
  'description': 'Total gross bookings value generated.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'SHOPPING SESSIONS',
  'description': 'App sessions where a rider browsed, not necessarily requesting a ride.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'RIDERS WITH SESSIONS',
  'description': 'Unique riders who opened a session.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'REQUESTING SESSIONS',
  'description': 'Sessions where the rider went on to request a ride.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'REQUESTS',
  'description': 'Total ride requests made.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'ACTIVE DRIVERS',
  'description': 'Unique drivers who were online during the period.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'SUPPLY HOURS',
  'description': 'Total hours drivers spent online and available.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'C/R',
  'description': 'Completion rate: completed trips over requests.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'C/RS',
  'description': 'Completion rate: completed trips over requesting sessions.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'RS/SS',
  'description': 'Conversion rate: requesting sessions over shopping sessions.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'C/SS',
  'description': 'Completion rate: completed trips over shopping sessions.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'ACCEPTANCE RATE',
  'description': 'Share of requests accepted by drivers.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'DRIVER CANCELATION',
  'description': 'Share of trips cancelled by drivers.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'SUPPLY UTILIZATION',
  'description': 'Share of available driver supply hours actually used.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'NPI',
  'description': 'Placeholder — confirm real definition.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'DRIVER PAYMENTS (AS % OF GB)',
  'description': 'Driver earnings as a percentage of gross bookings.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'RIDER INCENTIVES AND PROMOTIONS (AS % OF GB)',
  'description': 'Rider-side incentives/promos as a percentage of gross bookings.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'DRIVER INCENTIVES AND PROMOTIONS (AS % OF GB)',
  'description': 'Driver-side incentives/promos as a percentage of gross bookings.',
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'},
 {'name': 'TAKE RATE (AS % OF GB)',
  'description': "Platform's take rate as a percentage of gross bookings.",
  'completeness': '100',
  'nulls': 0,
  'total': 168,
  'status': 'ok'}]

## 10. Build the Data Nulls card (`data_quality.html`)
Title, description, KPI card, and a dropdown to drill into each column \u2014 all populated from `column_stats` above, so editing the CSV updates this automatically.

In [11]:
# ============================================
# CONFIGURE HERE: titles, copy and colors
# ============================================
uber_blue = "#276EF1"
uber_green = "#3AA76D"
uber_yellow = "#FFC043"
uber_red = "#D44333"

page_title = "DATA NULLS"
page_description = (
    "This check scans every column in the dataset for missing values, "
    "so you can see at a glance which fields are complete and which ones "
    "need attention. Pick a column below to see its details."
)

status_colors = {"ok": uber_green, "warn": uber_yellow, "bad": uber_red}
status_labels = {"ok": "OK", "warn": "Review", "bad": "Critical"}

column_stats_json = json.dumps(column_stats)

data_quality_html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Data Quality</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; }}
  body {{ background: #f3f4f6; padding: 32px; }}
  .wrap {{ max-width: 640px; margin: 0 auto; }}
  h2 {{ color: #111; margin-bottom: 8px; text-align: center; text-transform: uppercase; letter-spacing: 0.5px; }}
  .description {{ color: #6b7280; font-size: 14px; margin-bottom: 24px; line-height: 1.5; text-align: center; }}

  .hero-card {{
    background: {uber_blue};
    color: #FFFFFF;
    border-radius: 16px;
    padding: 20px 32px;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: 4px;
    margin: 0 auto 24px auto;
    max-width: 280px;
  }}
  .hero-card .hero-number {{ font-size: 40px; font-weight: 700; line-height: 1; }}
  .hero-card .hero-label {{ font-size: 13px; font-weight: 600; opacity: 0.95; }}
  .hero-card .hero-sub {{ font-size: 11px; opacity: 0.8; }}

  .section-card {{ background: white; border-radius: 12px; padding: 28px; box-shadow: 0 2px 10px rgba(0,0,0,0.06); }}
  .section-card label {{ font-size: 13px; color: #6b7280; display: block; margin-bottom: 8px; }}
  select {{
    width: 100%;
    padding: 10px 12px;
    border-radius: 8px;
    border: 1px solid #d1d5db;
    font-size: 14px;
    margin-bottom: 20px;
    background: white;
  }}

  .col-name {{ font-size: 18px; font-weight: 700; color: #111; margin-bottom: 10px; }}
  .metric-row {{ font-size: 14px; color: #374151; margin-bottom: 6px; }}
  .metric-label {{ color: #6b7280; }}
  #col-pct {{ font-weight: 700; }}
  .badge {{ padding: 3px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; }}
</style>
</head>
<body>
  <div class="wrap">
    <div class="section-card">
      <h2>{page_title}</h2>
      <p class="description">{page_description}</p>

      <div class="hero-card">
        <div class="hero-number">{completeness_pct_label}%</div>
        <div class="hero-label">Data Completeness</div>
        <div class="hero-sub">{summary_text}</div>
      </div>

      <label for="column-select">Choose a column</label>
      <select id="column-select" onchange="renderColumn(this.value)"></select>

      <div class="col-name" id="col-name"></div>
      <div class="metric-row"><span class="metric-label">Completion rate:</span> <span id="col-pct"></span> <span class="badge" id="col-badge"></span></div>
      <div class="metric-row"><span class="metric-label">Total nulls:</span> <span id="col-nulls"></span></div>
      <div class="metric-row"><span class="metric-label">Total data:</span> <span id="col-total"></span></div>
    </div>
  </div>

<script>
  const columnStats = {column_stats_json};
  const statusColors = {{ ok: "{uber_green}", warn: "{uber_yellow}", bad: "{uber_red}" }};
  const statusLabels = {{ ok: "OK", warn: "Review", bad: "Critical" }};

  const select = document.getElementById('column-select');
  columnStats.forEach(function(col) {{
    const opt = document.createElement('option');
    opt.value = col.name;
    opt.textContent = col.name;
    select.appendChild(opt);
  }});

  function renderColumn(name) {{
    const col = columnStats.find(function(c) {{ return c.name === name; }});
    if (!col) return;
    document.getElementById('col-name').textContent = col.name;
    document.getElementById('col-pct').textContent = col.completeness + "%";
    document.getElementById('col-pct').style.color = statusColors[col.status];
    document.getElementById('col-nulls').textContent = col.nulls;
    document.getElementById('col-total').textContent = col.total;
    const badge = document.getElementById('col-badge');
    badge.textContent = statusLabels[col.status];
    badge.style.background = statusColors[col.status] + "22";
    badge.style.color = statusColors[col.status];
  }}

  renderColumn(columnStats[0].name);
</script>
</body>
</html>
'''

with open("data_quality.html", "w", encoding="utf-8") as f:
    f.write(data_quality_html)

print("data_quality.html generated with", len(column_stats), "columns")

data_quality.html generated with 22 columns

## 11. Data Quality — month coverage per city
For each city: how many months it *should* have (based on the full date range in the dataset), how many it actually has, and any missing or duplicated months. Feeds the "Month Coverage" table in `data_quality.html`.

In [12]:
from collections import Counter

all_months = sorted(df_quality['MONTH'].unique())
expected_months = len(all_months)
first_month = all_months[0]
last_month = all_months[-1]

city_coverage = []
for city, g in df_quality.groupby('CITY'):
    months_list = g['MONTH'].tolist()
    unique_months = sorted(set(months_list))
    missing = sorted(set(all_months) - set(unique_months))
    dupes = sorted([m for m, c in Counter(months_list).items() if c > 1])
    coverage_pct = round(len(unique_months) / expected_months * 100, 1)
    coverage_label = f"{coverage_pct:.0f}" if coverage_pct == int(coverage_pct) else f"{coverage_pct}"

    if coverage_pct >= ok_threshold:
        cov_status = "ok"
    elif coverage_pct >= warn_threshold:
        cov_status = "warn"
    else:
        cov_status = "bad"

    city_coverage.append({
        "city": city,
        "expected_months": expected_months,
        "rows_found": len(g),
        "unique_months": len(unique_months),
        "coverage": coverage_label,
        "missing_months": ", ".join(missing) if missing else "None",
        "duplicate_months": ", ".join(dupes) if dupes else "None",
        "status": cov_status,
    })

city_coverage

[{'city': 'Azteca',
  'expected_months': 21,
  'rows_found': 21,
  'unique_months': 21,
  'coverage': '100',
  'missing_months': 'None',
  'duplicate_months': 'None',
  'status': 'ok'},
 {'city': 'Lusail',
  'expected_months': 21,
  'rows_found': 21,
  'unique_months': 21,
  'coverage': '100',
  'missing_months': 'None',
  'duplicate_months': 'None',
  'status': 'ok'},
 {'city': 'Maracanã',
  'expected_months': 21,
  'rows_found': 21,
  'unique_months': 21,
  'coverage': '100',
  'missing_months': 'None',
  'duplicate_months': 'None',
  'status': 'ok'},
 {'city': 'Old Trafford',
  'expected_months': 21,
  'rows_found': 21,
  'unique_months': 21,
  'coverage': '100',
  'missing_months': 'None',
  'duplicate_months': 'None',
  'status': 'ok'},
 {'city': 'Rose Bowl',
  'expected_months': 21,
  'rows_found': 21,
  'unique_months': 21,
  'coverage': '100',
  'missing_months': 'None',
  'duplicate_months': 'None',
  'status': 'ok'},
 {'city': 'San Siro',
  'expected_months': 21,
  'rows_found': 21,
  'unique_months': 21,
  'coverage': '100',
  'missing_months': 'None',
  'duplicate_months': 'None',
  'status': 'ok'},
 {'city': 'Santiago Bernabeu',
  'expected_months': 21,
  'rows_found': 21,
  'unique_months': 21,
  'coverage': '100',
  'missing_months': 'None',
  'duplicate_months': 'None',
  'status': 'ok'},
 {'city': 'Vila Belmiro',
  'expected_months': 21,
  'rows_found': 21,
  'unique_months': 21,
  'coverage': '100',
  'missing_months': 'None',
  'duplicate_months': 'None',
  'status': 'ok'}]

## 12. Add the Month Coverage table to `data_quality.html`
Appends a second section-card below the existing one, built from `city_coverage` above — so it updates automatically if the CSV changes.

In [13]:
# ============================================
# CONFIGURE HERE: table title and copy
# ============================================
coverage_title = "MONTH COVERAGE"
coverage_description = (
    f"Checks that every city has a row for each month between {first_month} and {last_month} "
    "(the full date range in the dataset), and flags any missing or duplicated months."
)

city_coverage_json = json.dumps(city_coverage)

coverage_rows_html = ""
for row in city_coverage:
    color = {"ok": uber_green, "warn": uber_yellow, "bad": uber_red}[row["status"]]
    badge_bg = color + "1A"
    coverage_rows_html += f'''
        <tr>
          <td class="city-cell">{row["city"]}</td>
          <td class="num-cell">{row["expected_months"]}</td>
          <td class="num-cell">{row["rows_found"]}</td>
          <td class="num-cell">{row["unique_months"]}</td>
          <td class="num-cell"><span class="cov-badge" style="color:{color}; background:{badge_bg};">{row["coverage"]}%</span></td>
          <td class="muted-cell">{row["missing_months"]}</td>
          <td class="muted-cell">{row["duplicate_months"]}</td>
        </tr>'''

coverage_section_html = f'''
    <div class="section-card" style="margin-top:24px;">
      <h2>{coverage_title}</h2>
      <p class="description">{coverage_description}</p>
      <div class="table-scroll">
      <table class="coverage-table">
        <thead>
          <tr>
            <th>City</th>
            <th>Expected Months</th>
            <th>Rows Found</th>
            <th>Unique Months</th>
            <th>Coverage %</th>
            <th>Missing Months</th>
            <th>Duplicate Months</th>
          </tr>
        </thead>
        <tbody>{coverage_rows_html}
        </tbody>
      </table>
      </div>
    </div>'''

# Insert the new section right before the closing </div> of .wrap, and add its CSS
# right before </style>, without touching anything already built above.
coverage_css = '''
  .wrap { max-width: 820px; }
  .table-scroll { overflow-x: auto; border-radius: 10px; border: 1px solid #f0f0f0; }
  .coverage-table { width: 100%; border-collapse: collapse; font-size: 13px; }
  .coverage-table th, .coverage-table td { padding: 12px 14px; white-space: nowrap; }
  .coverage-table thead th {
    text-align: center;
    color: #6b7280;
    font-weight: 700;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.4px;
    background: #f9fafb;
    border-bottom: 2px solid #eef0f3;
  }
  .coverage-table thead th:first-child { text-align: left; }
  .coverage-table tbody tr { border-bottom: 1px solid #f2f3f5; }
  .coverage-table tbody tr:last-child { border-bottom: none; }
  .coverage-table tbody tr:nth-child(even) { background: #fafbfc; }
  .coverage-table tbody tr:hover { background: #f2f6fe; }
  .city-cell { font-weight: 600; color: #111; text-align: left; }
  .num-cell { text-align: center; color: #374151; }
  .muted-cell { text-align: center; color: #9ca3af; font-size: 12px; }
  .cov-badge { display: inline-block; padding: 4px 12px; border-radius: 999px; font-weight: 700; }
'''

data_quality_html = data_quality_html.replace("</style>", coverage_css + "</style>")
data_quality_html = data_quality_html.replace("  </div>\n\n<script>", "  </div>\n" + coverage_section_html + "\n\n<script>")

with open("data_quality.html", "w", encoding="utf-8") as f:
    f.write(data_quality_html)

print("Month Coverage section added for", len(city_coverage), "cities")

Month Coverage section added for 8 cities

## 13. Data Quality — data type correctness
For each column: what type it *should* be (based on what the data represents) vs. what type it actually is in the CSV, and whether that's a real issue (e.g. numbers stored as text because of thousand-separator commas or a trailing `%` sign).

In [14]:
def classify_column(series):
    """Detects the real format/shape of a column's values \u2014 does NOT strip
    the % sign or commas, it only checks whether the cell's shape matches
    a date, a percentage, or a number. Handles mixed/inconsistent columns too."""
    if pd.api.types.is_numeric_dtype(series):
        return "numeric_native"

    s = series.astype(str).str.strip()
    frac_date = s.str.match(r"^\d{4}-\d{2}$").mean()
    frac_percent = s.str.match(r"^-?[\d,]+(\.\d+)?%$").mean()
    cleaned = s.str.replace(",", "", regex=False)
    frac_numeric = cleaned.str.match(r"^-?\d+(\.\d+)?$").mean()

    if frac_date == 1.0:
        return "date_text"
    if frac_percent == 1.0:
        return "percent_text"
    if frac_numeric == 1.0:
        return "numeric_text"

    # Not 100% consistent \u2014 flag as mixed rather than assume plain text
    if frac_percent > 0:
        return "inconsistent_percent"
    if frac_numeric > 0:
        return "inconsistent_numeric"
    if frac_date > 0:
        return "inconsistent_date"
    return "text"

# ============================================
# CONFIGURE HERE: what each detected shape means, and what a
# spreadsheet (Excel/Numbers) actually shows for it \u2014 verified by
# hand against a real spreadsheet, column by column:
#   - commas  (3,005,706)  -> Excel shows "Number"      -> OK
#   - percent (78.20%)     -> Excel shows "Percentage"  -> OK
#   - plain decimal (1.03) -> Excel shows "General"      -> NOT OK
#     (no comma/% means Excel never applies a real Number format)
#   - YYYY-MM (2022-01)    -> Excel shows "General" (as text) -> NOT OK
# "General" only counts as OK for columns that are supposed to be Text.
# ============================================
type_meta = {
    "date_text":            {"expected": "Date",       "actual": "General",    "issue": True},
    "text":                 {"expected": "Text",       "actual": "Text",       "issue": False},
    "numeric_text":         {"expected": "Number",     "actual": "Number",     "issue": False},
    "percent_text":         {"expected": "Percentage", "actual": "Percentage", "issue": False},
    "numeric_native":       {"expected": "Number",     "actual": "General",    "issue": True},
    "inconsistent_date":    {"expected": "Date",       "actual": "Mixed",      "issue": True},
    "inconsistent_numeric": {"expected": "Number",     "actual": "Mixed",      "issue": True},
    "inconsistent_percent": {"expected": "Percentage", "actual": "Mixed",      "issue": True},
}

type_stats = []
for col in df_quality.columns:
    kind = classify_column(df_quality[col])
    meta = type_meta[kind]

    if kind == "date_text":
        vals = sorted(df_quality[col].unique())
        values_label = f"{len(vals)} distinct values ({vals[0]} to {vals[-1]})"
    elif kind == "text":
        values_label = f"{df_quality[col].nunique()} distinct values"
    elif kind == "numeric_text":
        nums = df_quality[col].astype(str).str.replace(",", "", regex=False).astype(float)
        values_label = f"min: {nums.min():,.0f}  max: {nums.max():,.0f}"
    elif kind == "percent_text":
        nums = df_quality[col].astype(str).str.replace("%", "", regex=False).astype(float)
        values_label = f"min: {nums.min():.1f}%  max: {nums.max():.1f}%"
    elif kind == "numeric_native":
        nums = df_quality[col]
        values_label = f"min: {nums.min():.2f}  max: {nums.max():.2f}"
    else:
        # inconsistent_* columns: just show how many distinct raw values exist
        values_label = f"{df_quality[col].nunique()} distinct raw values (mixed formats)"

    type_stats.append({
        "column": col,
        "expected_type": meta["expected"],
        "actual_type": meta["actual"],
        "issue": meta["issue"],
        "values": values_label,
    })

type_stats

[{'column': 'MONTH',
  'expected_type': 'Date',
  'actual_type': 'General',
  'issue': True,
  'values': '21 distinct values (2022-01 to 2023-09)'},
 {'column': 'CITY',
  'expected_type': 'Text',
  'actual_type': 'Text',
  'issue': False,
  'values': '8 distinct values'},
 {'column': 'TRIPS',
  'expected_type': 'Number',
  'actual_type': 'Number',
  'issue': False,
  'values': 'min: 1,533,078  max: 15,078,245'},
 {'column': 'GROSS BOOKINGS (GB)',
  'expected_type': 'Number',
  'actual_type': 'Number',
  'issue': False,
  'values': 'min: 25,315,829  max: 341,153,811'},
 {'column': 'SHOPPING SESSIONS',
  'expected_type': 'Number',
  'actual_type': 'Number',
  'issue': False,
  'values': 'min: 2,692,591  max: 28,135,176'},
 {'column': 'RIDERS WITH SESSIONS',
  'expected_type': 'Number',
  'actual_type': 'Number',
  'issue': False,
  'values': 'min: 406,844  max: 3,264,081'},
 {'column': 'REQUESTING SESSIONS',
  'expected_type': 'Number',
  'actual_type': 'Number',
  'issue': False,
  'values': 'min: 1,638,051  max: 16,723,285'},
 {'column': 'REQUESTS',
  'expected_type': 'Number',
  'actual_type': 'Number',
  'issue': False,
  'values': 'min: 1,859,779  max: 18,791,835'},
 {'column': 'ACTIVE DRIVERS',
  'expected_type': 'Number',
  'actual_type': 'Number',
  'issue': False,
  'values': 'min: 8,742  max: 90,278'},
 {'column': 'SUPPLY HOURS',
  'expected_type': 'Number',
  'actual_type': 'Number',
  'issue': False,
  'values': 'min: 824,750  max: 9,312,092'},
 {'column': 'C/R',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 59.7%  max: 90.7%'},
 {'column': 'C/RS',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 81.0%  max: 96.8%'},
 {'column': 'RS/SS',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 52.4%  max: 67.8%'},
 {'column': 'C/SS',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 46.5%  max: 65.3%'},
 {'column': 'ACCEPTANCE RATE',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 17.0%  max: 46.0%'},
 {'column': 'DRIVER CANCELATION',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 13.0%  max: 32.0%'},
 {'column': 'SUPPLY UTILIZATION',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 55.0%  max: 81.0%'},
 {'column': 'NPI',
  'expected_type': 'Number',
  'actual_type': 'General',
  'issue': True,
  'values': 'min: 0.92  max: 1.10'},
 {'column': 'DRIVER PAYMENTS (AS % OF GB)',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 69.0%  max: 79.9%'},
 {'column': 'RIDER INCENTIVES AND PROMOTIONS (AS % OF GB)',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: -8.5%  max: 17.4%'},
 {'column': 'DRIVER INCENTIVES AND PROMOTIONS (AS % OF GB)',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 0.0%  max: 9.1%'},
 {'column': 'TAKE RATE (AS % OF GB)',
  'expected_type': 'Percentage',
  'actual_type': 'Percentage',
  'issue': False,
  'values': 'min: 4.2%  max: 24.3%'}]

## 15. Data Quality — build a cleaned copy of the dataset
Fixes what section 13 flagged: strips commas from numeric columns, strips `%` from rate columns, and parses MONTH as a real date — reusing the same `classify_column` detection from section 13. Saves the result as `dataset_clean.csv`, a separate file (the original `dataset.csv` is never modified).

In [15]:
# ============================================
# CONFIGURE HERE: only touch a column's actual VALUES when the raw
# format is genuinely broken (mixed/inconsistent formats within the
# same column). A column that is internally consistent \u2014 even if
# Excel shows it as "General" (like MONTH or NPI) \u2014 is copied
# unchanged: nothing is stripped, reformatted, or padded just to make
# it match its expected type.
# ============================================
df_clean = df_quality.copy()
column_actions = {}

for col in df_quality.columns:
    kind = classify_column(df_quality[col])

    if kind == "inconsistent_date":
        df_clean[col] = pd.to_datetime(df_quality[col], format="%Y-%m", errors="coerce").dt.strftime("%Y-%m-01")
        column_actions[col] = "Parsed as date (had mixed formats)"
    elif kind == "inconsistent_numeric":
        df_clean[col] = pd.to_numeric(df_quality[col].astype(str).str.replace(",", "", regex=False), errors="coerce")
        column_actions[col] = "Removed commas (had mixed formats)"
    elif kind == "inconsistent_percent":
        df_clean[col] = pd.to_numeric(df_quality[col].astype(str).str.replace("%", "", regex=False), errors="coerce")
        column_actions[col] = "Removed % sign (had mixed formats)"
    else:
        # date_text, numeric_text, percent_text, numeric_native, text:
        # already internally consistent \u2014 cell content copied as-is, untouched.
        df_clean[col] = df_quality[col]
        column_actions[col] = "No changes needed"

df_clean.head()

,MONTH,CITY,TRIPS,GROSS BOOKINGS (GB),SHOPPING SESSIONS,RIDERS WITH SESSIONS,REQUESTING SESSIONS,REQUESTS,ACTIVE DRIVERS,SUPPLY HOURS,...,RS/SS,C/SS,ACCEPTANCE RATE,DRIVER CANCELATION,SUPPLY UTILIZATION,NPI,DRIVER PAYMENTS (AS % OF GB),RIDER INCENTIVES AND PROMOTIONS (AS % OF GB),DRIVER INCENTIVES AND PROMOTIONS (AS % OF GB),TAKE RATE (AS % OF GB)
0,2022-01,Vila Belmiro,"3,005,706","56,529,569","5,283,006","711,432","3,257,826","3,844,423","18,795","1,564,816",...,61.7%,56.9%,23.0%,20.0%,63.0%,1.03,73.5%,5.7%,5.1%,14.2%
1,2022-01,Rose Bowl,"1,533,078","25,315,829","2,692,591","406,844","1,638,051","1,859,779","8,742","824,750",...,60.8%,56.9%,34.0%,15.0%,59.0%,0.98,76.3%,-3.3%,4.3%,20.5%
2,2022-01,San Siro,"8,108,570","155,667,588","14,385,079","1,609,850","8,570,326","9,515,128","50,056","4,187,961",...,59.6%,56.4%,44.0%,22.0%,73.0%,1.02,78.8%,4.9%,3.6%,10.6%
3,2022-01,Lusail,"2,163,550","38,225,180","3,939,724","493,960","2,348,175","2,859,544","10,845","1,074,968",...,59.6%,54.9%,25.0%,20.0%,70.0%,1.05,76.8%,6.2%,3.6%,11.8%
4,2022-01,Old Trafford,"11,042,462","206,436,144","19,113,887","2,553,885","11,801,188","13,152,423","63,551","5,202,255",...,61.7%,57.8%,46.0%,27.0%,77.0%,1.05,75.6%,-1.4%,3.4%,17.0%

## 16. Save the cleaned dataset
Writes `dataset_clean.csv` next to `dataset.csv`. Upload this new file to the repo alongside the others — it doesn't replace `dataset.csv`, it's a second, ready-to-analyze version.

In [16]:
df_clean.to_csv("dataset_clean.csv", index=False)
print("Saved dataset_clean.csv with", len(df_clean), "rows and", len(df_clean.columns), "columns")

Saved dataset_clean.csv with 168 rows and 22 columns

## 17. Before / after comparison
For each column: the transformation applied, a real example of how the raw value looked, how the corrected value looks, and its new type. Feeds the last section of `data_quality.html`.

In [17]:
before_after = []
for col in df_quality.columns:
    kind = classify_column(df_quality[col])
    meta = type_meta[kind]
    raw_example = str(df_quality[col].iloc[0])
    clean_example = str(df_clean[col].iloc[0])
    before_after.append({
        "column": col,
        "action": column_actions[col],
        "raw_example": raw_example,
        "clean_example": clean_example,
        "new_type": meta["expected"],  # after cleaning, actual type now matches expected
    })

before_after

[{'column': 'MONTH',
  'action': 'No changes needed',
  'raw_example': '2022-01',
  'clean_example': '2022-01',
  'new_type': 'Date'},
 {'column': 'CITY',
  'action': 'No changes needed',
  'raw_example': 'Vila Belmiro',
  'clean_example': 'Vila Belmiro',
  'new_type': 'Text'},
 {'column': 'TRIPS',
  'action': 'No changes needed',
  'raw_example': '3,005,706',
  'clean_example': '3,005,706',
  'new_type': 'Number'},
 {'column': 'GROSS BOOKINGS (GB)',
  'action': 'No changes needed',
  'raw_example': '56,529,569',
  'clean_example': '56,529,569',
  'new_type': 'Number'},
 {'column': 'SHOPPING SESSIONS',
  'action': 'No changes needed',
  'raw_example': '5,283,006',
  'clean_example': '5,283,006',
  'new_type': 'Number'},
 {'column': 'RIDERS WITH SESSIONS',
  'action': 'No changes needed',
  'raw_example': '711,432',
  'clean_example': '711,432',
  'new_type': 'Number'},
 {'column': 'REQUESTING SESSIONS',
  'action': 'No changes needed',
  'raw_example': '3,257,826',
  'clean_example': '3,257,826',
  'new_type': 'Number'},
 {'column': 'REQUESTS',
  'action': 'No changes needed',
  'raw_example': '3,844,423',
  'clean_example': '3,844,423',
  'new_type': 'Number'},
 {'column': 'ACTIVE DRIVERS',
  'action': 'No changes needed',
  'raw_example': '18,795',
  'clean_example': '18,795',
  'new_type': 'Number'},
 {'column': 'SUPPLY HOURS',
  'action': 'No changes needed',
  'raw_example': '1,564,816',
  'clean_example': '1,564,816',
  'new_type': 'Number'},
 {'column': 'C/R',
  'action': 'No changes needed',
  'raw_example': '78.2%',
  'clean_example': '78.2%',
  'new_type': 'Percentage'},
 {'column': 'C/RS',
  'action': 'No changes needed',
  'raw_example': '92.3%',
  'clean_example': '92.3%',
  'new_type': 'Percentage'},
 {'column': 'RS/SS',
  'action': 'No changes needed',
  'raw_example': '61.7%',
  'clean_example': '61.7%',
  'new_type': 'Percentage'},
 {'column': 'C/SS',
  'action': 'No changes needed',
  'raw_example': '56.9%',
  'clean_example': '56.9%',
  'new_type': 'Percentage'},
 {'column': 'ACCEPTANCE RATE',
  'action': 'No changes needed',
  'raw_example': '23.0%',
  'clean_example': '23.0%',
  'new_type': 'Percentage'},
 {'column': 'DRIVER CANCELATION',
  'action': 'No changes needed',
  'raw_example': '20.0%',
  'clean_example': '20.0%',
  'new_type': 'Percentage'},
 {'column': 'SUPPLY UTILIZATION',
  'action': 'No changes needed',
  'raw_example': '63.0%',
  'clean_example': '63.0%',
  'new_type': 'Percentage'},
 {'column': 'NPI',
  'action': 'No changes needed',
  'raw_example': '1.03',
  'clean_example': '1.03',
  'new_type': 'Number'},
 {'column': 'DRIVER PAYMENTS (AS % OF GB)',
  'action': 'No changes needed',
  'raw_example': '73.5%',
  'clean_example': '73.5%',
  'new_type': 'Percentage'},
 {'column': 'RIDER INCENTIVES AND PROMOTIONS (AS % OF GB)',
  'action': 'No changes needed',
  'raw_example': '5.7%',
  'clean_example': '5.7%',
  'new_type': 'Percentage'},
 {'column': 'DRIVER INCENTIVES AND PROMOTIONS (AS % OF GB)',
  'action': 'No changes needed',
  'raw_example': '5.1%',
  'clean_example': '5.1%',
  'new_type': 'Percentage'},
 {'column': 'TAKE RATE (AS % OF GB)',
  'action': 'No changes needed',
  'raw_example': '14.2%',
  'clean_example': '14.2%',
  'new_type': 'Percentage'}]

## 18. Add the combined Data Type Check section to `data_quality.html`
One merged section (instead of two separate tables): a hero card showing how many columns need cleaning — with the breakdown by type as a small subtitle — and a table listing only the columns that actually have an issue, with their raw → corrected example. Built from `type_stats` and `before_after` above.

In [18]:
# ============================================
# CONFIGURE HERE: title and copy
# ============================================
combined_title = "DATA TYPE CHECK"
combined_description = (
    "Whether each column has the type it should when opened in a spreadsheet, "
    "and what changed to fix the ones that don't."
)

n_issues = sum(1 for r in type_stats if r["issue"])
n_total = len(type_stats)

# Small breakdown by type, e.g. "8 Number \u00b7 10 Percentage \u00b7 1 Text \u00b7 2 General"
from collections import Counter
type_counts = Counter(r["actual_type"] for r in type_stats)
breakdown_label = " \u00b7 ".join(f"{count} {label}" for label, count in type_counts.items())

issue_columns = [r["column"] for r in type_stats if r["issue"]]
before_after_by_col = {r["column"]: r for r in before_after}

issue_rows_html = ""
for col in issue_columns:
    ba = before_after_by_col[col]
    expected = next(r["expected_type"] for r in type_stats if r["column"] == col)
    issue_rows_html += f'''
        <tr>
          <td class="city-cell">{col}</td>
          <td class="num-cell">{expected}</td>
          <td class="muted-cell">{ba["raw_example"]} \u2192 {ba["clean_example"]}</td>
        </tr>'''

combined_section_html = f'''
    <div class="section-card" style="margin-top:24px;">
      <h2>{combined_title}</h2>
      <p class="description">{combined_description}</p>

      <div class="hero-card">
        <div class="hero-number">{n_issues} / {n_total}</div>
        <div class="hero-label">Columns Need Cleaning</div>
        <div class="hero-sub">{breakdown_label}</div>
      </div>

      <div class="table-scroll">
      <table class="coverage-table">
        <thead>
          <tr>
            <th>Column</th>
            <th>Expected</th>
            <th>Raw \u2192 Corrected</th>
          </tr>
        </thead>
        <tbody>{issue_rows_html}
        </tbody>
      </table>
      </div>
    </div>'''

data_quality_html = data_quality_html.replace("  </div>\n\n<script>", "  </div>\n" + combined_section_html + "\n\n<script>")

with open("data_quality.html", "w", encoding="utf-8") as f:
    f.write(data_quality_html)

print("Combined Data Type Check section added:", n_issues, "of", n_total, "columns flagged")

Combined Data Type Check section added: 2 of 22 columns flagged

## 19. Save `dataset_clean.xlsx` — same content, corrected cell type
A CSV can't store a cell's *type* separately from its text \u2014 Excel only guesses General/Number/Date by sniffing the pattern when it opens the file. To actually force a cell's type without touching its value, the file has to be a real spreadsheet (`.xlsx`), which stores format and value separately. This cell writes every value **exactly** as it already is in `df_clean` (no stripped commas, no added days, no rounded decimals) and only sets the number format metadata for MONTH (→ Short Date) and NPI (→ Number).

**Note:** MONTH's value stays the text `2022-01` (no day added, as requested) \u2014 Excel can only *visually* render a cell as a date if the stored value is a real date serial number, so even with the Short Date format applied, Excel will likely still display `2022-01` as plain text. The format metadata will say Short Date either way; please check in your actual Excel/Numbers and tell me what you see.

In [19]:
import openpyxl
from openpyxl.utils.dataframe import dataframe_to_rows

# ============================================
# CONFIGURE HERE: which columns get which explicit format,
# and the exact format code to use for each
# ============================================
column_number_formats = {
    "MONTH": "mm/dd/yyyy",  # Short Date
    "NPI":   "0.00",        # Number (matches NPI's existing 2-decimal values)
}

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "dataset_clean"

for row in dataframe_to_rows(df_clean, index=False, header=True):
    ws.append(row)

header = [cell.value for cell in ws[1]]
col_letter = {name: openpyxl.utils.get_column_letter(i + 1) for i, name in enumerate(header)}

for col_name, fmt in column_number_formats.items():
    letter = col_letter[col_name]
    for row_idx in range(2, ws.max_row + 1):
        ws[f"{letter}{row_idx}"].number_format = fmt

wb.save("dataset_clean.xlsx")
print("Saved dataset_clean.xlsx \u2014 values unchanged, MONTH tagged Short Date, NPI tagged Number")

Saved dataset_clean.xlsx — values unchanged, MONTH tagged Short Date, NPI tagged Number